### PR TITLE
Add imagePullSecrets support

### PR DESCRIPTION
**Pull request by bFekete**
### Description

- Adds `imagePullSecrets` to allow users to specify credentials for pulling down images. Useful when images used by this chart, are mirrored into a private registry.

### Usage Example

Chart parses correctly as shown below. 

```sh
$ helm template . --set-json 'imagePullSecrets=[{"name": "cred"}, {"name": "test"}]' | yq  'select(document_index == 9) | .spec.template.spec'
imagePullSecrets:
  - name: cred
  - name: test
containers:
  - name: manager
    image: hashicorp/terraform-cloud-operator:2.2.0
...
```

### Release Note

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-cloud-operator/blob/main/CHANGELOG.md):

```release-note
Adds `imagePullSecrets` to allow users to specify credentials for pulling down images.
```

### References

 - Fixes: https://github.com/hashicorp/terraform-cloud-operator/issues/161

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### CODE REVIEW

**Comment by arybolovlev** [comment]
Hi @bFekete,

Thank you for your contribution. All in all, looks good. I am now working on changelog and Helm chart docs automation and thus postpone approving your PR for a few more days. Once I am done, I will come back to you with a few change proposals and we should be good to go!

TY!

**Comment by arybolovlev** [comment]
Hi @bFekete,

Could you please rebase your PR to pick up the latest changes in the repo?

Once this is done, please do the following:

- Add the following line to `values.yaml` before a new attribute that you add: `# -- Reference to one or more secrets essential for pulling container images.` It would serve as a documentation.
- Run `make helm-docs` to update the Helm chart README file.
- Run `changie new`(you might need to [install](https://changie.dev/guide/installation/) it first) and chose `ENHANCEMENTS`. Body would be the following:
 ~~~
 `Helm Chart`: Add a new attribute `imagePullSecrets` to enable pulling the Operator images from private repositories.
 ~~~
- Once it is all done, push your changes here.

Thanks!

**Comment by bFekete** [comment]
> Hi @bFekete,
> 
> Could you please rebase your PR to pick up the latest changes in the repo?
> 
> Once this is done, please do the following:
> 
>     * Add the following line to `values.yaml` before a new attribute that you add: `# -- Reference to one or more secrets essential for pulling container images.` It would serve as a documentation.
> 
>     * Run `make helm-docs` to update the Helm chart README file.
> 
>     * Run `changie new`(you might need to [install](https://changie.dev/guide/installation/) it first) and chose `ENHANCEMENTS`. Body would be the following:
> 
> 
> ```
> `Helm Chart`: Add a new attribute `imagePullSecrets` to enable pulling the Operator images from private repositories.
> ```
> 
>     * Once it is all done, push your changes here.
> 
> 
> Thanks!

Done

**Review by arybolovlev — APPROVED** [review]
Thank you, @bFekete! 🚀

**Pull request merged**
